name: local-test

secrets:
  MY_SECRET:
    environment: MY_SECRET

services:

  hello-world:
    build:
      args:
        BIN: hello-world
      context: ..
      dockerfile: ./docker/Dockerfile
      secrets:
        - MY_SECRET
      target: hello-world
    environment:
      - RUST_BACKTRACE=1

  goodbye-world:
    build:
      args:
        BIN: goodbye-world
      context: ..
      dockerfile: ./docker/Dockerfile
      target: goodbye-world
    environment:
      - RUST_BACKTRACE=1

  hasta-la-vista:
    build:
      args:
        BIN: hasta-la-vista
      context: ..
      dockerfile: ./docker/Dockerfile
      target: hasta-la-vista
    environment:
      - RUST_BACKTRACE=1
