name: docker

on:
  push:
    tags:
      - '*[v]?[0-9]+.[0-9]+.[0-9]+'

jobs:
  pkg-info:
    runs-on: ubuntu-latest
    outputs:
      package: ${{ steps.pkg_info.outputs.package }}
      version: ${{ steps.pkg_info.outputs.version }}
      dockerfile: ${{ steps.pkg_info.outputs.file }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get package info
        id: pkg_info
        env:
          GITHUB_REF: ${{ github.ref }}
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          PACKAGE=${TAG%-*}
          VERSION=${TAG##*-}
          DOCKERFILE=./docker/$PACKAGE/Dockerfile
          echo "package=$PACKAGE" >> $GITHUB_OUTPUT
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          if [[ -f $DOCKERFILE ]]; then
            echo "file=$DOCKERFILE" >> $GITHUB_OUTPUT
          fi

  docker-image:
    name: Build and push Docker images
    runs-on: ubuntu-latest
    needs: pkg-info
    # if: github.repository == '0xangelo/cargo-workspace-template'
    if: ${{ needs.pkg-info.outputs.dockerfile != null }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: angelovtt
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        env:
          MY_SECRET: ${{ secrets.HELLO_WORLD_SECRET }}
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ needs.pkg-info.outputs.dockerfile }}
          push: true
          tags: |
            angelovtt/${{ needs.pkg-info.outputs.package }}:${{ needs.pkg-info.outputs.version }}
            angelovtt/${{ needs.pkg-info.outputs.package }}:latest
          secret-envs: |
            MY_SECRET=MY_SECRET
          cache-from: |
            docker.io/angelovtt/${{ needs.pkg-info.outputs.package }}:latest
          cache-to: |
            docker.io/angelovtt/${{ needs.pkg-info.outputs.package }}:latest
