name: docker

on:
  push:
    tags:
      - '*[v]?[0-9]+.[0-9]+.[0-9]+'

jobs:
  pkg-info:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.pkg_info.outputs.version }}
      matrix: ${{ steps.pkg_info.outputs.bins }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Get package info
        id: pkg_info
        env:
          GITHUB_REF: ${{ github.ref }}
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          PACKAGE=${TAG%-*}
          VERSION=${TAG##*-}
          function bin_list_filtered {
            ALL=$(cargo metadata --no-deps --format-version=1 | jq -r ".packages[] | select(.name == \"$1\") | .targets[] | select(.kind == [\"bin\"]) | .name")
            unset BINS
            for bin in $ALL
            do
              grep -q "^FROM .* AS $bin\$" docker/Dockerfile && BINS="$BINS $bin"
            done
            echo $BINS | jq -R 'split(" ") | [.[] | select(length>0) | {bin: .}]'
          }
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "matrix={\"include\": $(bin_list_filtered $PACKAGE)}" >> "$GITHUB_OUTPUT"

  docker-image:
    # if: github.repository == '0xangelo/cargo-workspace-template'
    name: Build and push Docker images
    runs-on: ubuntu-latest
    needs: pkg-info
    strategy:
      matrix: ${{fromJson(needs.pkg-info.outputs.matrix)}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GitHub container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        env:
          MY_SECRET: ${{ secrets.HELLO_WORLD_SECRET }}
        uses: docker/build-push-action@v6
        with:
          # https://www.blacksmith.sh/blog/cache-is-king-a-guide-for-docker-layer-caching-in-github-actions
          cache-from: |-
            type=registry,ref=ghcr.io/0xangelo/${{ matrix.target }}:buildcache
          cache-to: |-
            type=registry,ref=ghcr.io/0xangelo/${{ matrix.target }}:buildcache,mode=max
          context: .
          file: docker/Dockerfile
          push: true
          secret-envs: |
            MY_SECRET=MY_SECRET
          tags: |
            ghcr.io/0xangelo/${{ matrix.target }}:${{ needs.pkg-info.outputs.version }}
            ghcr.io/0xangelo/${{ matrix.target }}:latest
          target: ${{ matrix.bin }}
